SET DATABASE SQL SYNTAX DB2 TRUE;
CREATE SCHEMA SMC AUTHORIZATION DBA;

CREATE TABLE SMC.SMC_PO_CATEGORY
(
   PO_CATEGORY_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   PO_CATEGORY varchar(20) NOT NULL,
   DESCRIPTION varchar(30),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_SUBCATEGORY
(
   PO_SUBCATEGORY_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   PO_SUBCATEGORY varchar(100) NOT NULL,
   DESCRIPTION varchar(50),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_CATEGORY_ASSOC
(
   PO_CATEGORY_ASSOC_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   PO_CATEGORY_ID int NOT NULL,
   PO_SUBCATEGORY_ID int NOT NULL,
   ACTIVE char(1) NOT NULL,
   MAKE_MODEL_YEAR_REQ char(1),
   VEHICLE_TYPE_REQ char(1),
   VEHICLE_SIZE_REQ char(1)
);

CREATE TABLE SMC.SMC_UNIT_MASTER
(
   MASTER_ID int NOT NULL GENERATED ALWAYS AS IDENTITY,
   CORP char(4) NOT NULL,
   PO_NUMBER int NOT NULL,
   UNIT_NUMBER char(10) NOT NULL,
   MISSING_INFO_COUNT int,
   UNIT_STATUS varchar(20),
   VEHICLE_SIZE varchar(10),
   DISTRICT_NUMBER varchar(4),
   IS_REBATE char(1),
   TRKDEVICE_ASSET varchar(10),
   IS_ROUTE_TRACKER_SENT char(1),
   CREATED_BY varchar(100),
   CREATED_DATE timestamp,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp,
   IS_REPLACED char(1) NOT NULL,
   VENDOR_ORDER_NUMBER varchar(15),
   IS_COMP_GENERATED varchar(1),
   IS_DATA_CONFLICT_CHECK varchar(1),
   IS_HOT char(1) NOT NULL,
   UNIT_SIGNATURE varchar(255),
   TEMPLATE_ID int,
   TEMPLATE_HASH varchar(32),
   IS_TEMPLATE_PROCESSED char(1),
   TEMPLATE_REFRESH_DATE TIMESTAMP
);

CREATE TABLE SMC.SMC_PURCHASING_HEADER
(
   HEADER_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   DCN int,
   SCH_A_NO varchar(10),
   CORP char(4) NOT NULL,
   PO_NUMBER int NOT NULL,
   PO_CATEGORY varchar(15),
   PO_SUB_CATEGORY varchar(100),
   CUSTOMER_NUMBER varchar(10),
   CUSTOMER_NAME varchar(100),
   VENDOR_NUMBER varchar(10),
   VENDOR_NAME varchar(100),
   OEM varchar(3),
   MODEL varchar(100),
   MODEL_YEAR varchar(4),
   VEHICLE_TYPE varchar(20),
   VEHICLE_USE varchar(20),
   DEAL_APPROVED_BY varchar(100) NOT NULL,
   COM_REQUEST_BUYER varchar(10) NOT NULL,
   CREATED_BY varchar(10),
   CREATED_DATE timestamp
);

CREATE TABLE SMC.SMC_VENDOR_MASTER
(
   VENDOR_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   CORP char(4) NOT NULL,
   VENDOR_NUMBER int NOT NULL,
   VENDOR_NAME varchar(100) NOT NULL,
   MFR varchar(10),
   NOTIFICATION_EXCEPTION char(1) NOT NULL,
   ANNUAL_AGREEMENT char(1) NOT NULL,
   PAYMENT_TERMS int,
   ADDRESS1 varchar(100) NOT NULL,
   ADDRESS2 varchar(100),
   CITY varchar(50) NOT NULL,
   STATE varchar(50) NOT NULL,
   ZIP varchar(15),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp,
   PLANNING_ANALYST int,
   SUPPLY_SPECIALIST int
);

CREATE TABLE SMC.SMC_UNIT_COMPONENT
(
   MASTER_ID int NOT NULL,
   COMPONENT_ID int NOT NULL,
   AVAIL_TO_OTHER_PO varchar(1) NOT NULL,
   EXPORT_TO_EXCEL varchar(1) NOT NULL,
   BASE_VISIBILITY varchar(1) NOT NULL,
   RULE_VISIBILITY varchar(1) NOT NULL,
   CONFLICT_STATUS varchar(2),
   FINAL_VISIBILITY varchar(1) NOT NULL,
   VALUE_PROVIDED varchar(1) NOT NULL,
   MODIFIED_DATE timestamp NOT NULL,
   CONSTRAINT null PRIMARY KEY (MASTER_ID,COMPONENT_ID)
);

CREATE TABLE SMC.SMC_COMPONENT_INFO_DETAILS
(
   COMPONENT_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   DISPLAY_NAME varchar(100),
   COMP_GROUP_ID int NOT NULL,
   COMPONENT_TYPE char(1) NOT NULL,
   IS_VEHICLE_COMP char(1) NOT NULL,
   VISIBILITY char(1) NOT NULL,
   COMPONENT_SEQUENCE int NOT NULL,
   GEN_MISSING_COUNT char(1) NOT NULL
);

CREATE TABLE SMC.SMC_TEMPLATE_MASTER
(
   TEMPLATE_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   TEMPLATE_HASH varchar(32),
   TEMPLATE_NAME varchar(50) NOT NULL,
   TEMPLATE_DESC varchar(100),
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10) NOT NULL,
   MODIFIED_DATE timestamp NOT NULL,
   PO_CATEGORY_ASSOC_ID int,
   STATUS varchar(1) NOT NULL
);

CREATE TABLE SMC.SMC_TEMPLATE_COMPONENTS
(
   TEMP_COMP_ID int NOT NULL GENERATED ALWAYS AS IDENTITY,
   TEMPLATE_ID int NOT NULL,
   COMPONENT_ID int NOT NULL,
   COMPONENT_ACCESS char(1) NOT NULL,
   AVAIL_TO_OTHER_PO char(1) NOT NULL,
   EXPORT_TO_EXCEL char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_COMPONENT_RULE_OVERRIDES
(
   CMP_RULES_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   CMP_VISIBLE_ID int,
   RULE_ID int NOT NULL,
   PRIORITY int,
   VISIBILITY_OVERRIDE char(1) NOT NULL,
   CREATED_BY varchar(10),
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp,
   TEMP_COMP_ID int
);

CREATE TABLE SMC.SMC_CMP_VISIBILITY_RULES_MASTER
(
   RULE_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   NAME char(50) NOT NULL,
   DESCRIPTION char(100) NOT NULL,
   CREATED_BY varchar(10),
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp,
   RULE_TYPE varchar(1) NOT NULL
);

CREATE TABLE SMC.SMC_CMP_VISIBILITY_RULES_DEFINITION
(
   RULE_DEF_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   RULE_ID int NOT NULL,
   CRITERIA_GROUP int NOT NULL,
   COMPONENT_ID decimal(9,0) NOT NULL,
   COMPONENT_TYPE varchar(1) NOT NULL,
   OPERAND varchar(2) NOT NULL,
   COMPONENT_VALUE varchar(30) NOT NULL,
   CREATED_BY varchar(10),
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_UNIT_MAP
(
   HEADER_INFO_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   MASTER_ID int NOT NULL,
   PO_NUMBER int NOT NULL,
   CO_NUMBER int NOT NULL,
   CANCEL_SEQ int NOT NULL,
   PAYABLE_STATUS varchar(20),
   BASE_PRICE decimal(15,2),
   FREIGHT_AMOUNT decimal(15,2),
   TOTAL_OTHER_PRICE decimal(15,2),
   TOTAL_UNIT_PRICE decimal(15,2),
   TOTAL_UNIT_AMT decimal(15,2),
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp NOT NULL
);

CREATE TABLE SMC.SMC_UNIT_DATE_INFO
(
   UNIT_DATE_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   MASTER_ID int NOT NULL,
   ORG_REQ_DATE date,
   ORG_EST_PROD_DATE date,
   ORG_EST_DEL_DATE date,
   EST_PROD_DATE date,
   ACT_PROD_DATE date,
   EST_DEL_DATE date,
   ACT_DEL_DATE date,
   PDI_CENTER_RECD date,
   PDI_CENTER_COMPLETED date,
   DELAY_TYPE int,
   DELAY_REASON int,
   DELAY_COMMENT varchar(1000),
   CREATED_BY varchar(100),
   CREATED_DATE timestamp,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp,
   COMM_REQ_ID int
);

CREATE TABLE SMC.SMC_GLOBAL_EXCEPTIONS
(
   GLOBAL_EXCEPTION_ID int NOT NULL GENERATED ALWAYS AS IDENTITY,
   COMPONENT_ID int NOT NULL,
   PROVIDER_PO_CATEGORY_ASSOC_ID int NOT NULL,
   PROVIDER_VENDOR_ID int NOT NULL,
   CREATED_BY varchar(100),
   NEW_EXCEPTION varchar(1),
   UNIT_SIGNATURE varchar(255) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100) NOT NULL
);

Create Table SMC.SMC_LOOKUP (
	LOOKUP_ID                     INTEGER             NOT NULL GENERATED ALWAYS AS IDENTITY,
	LOOKUP_NAME                   VARCHAR(50)         NOT NULL,
	LOOKUP_VALUE                  VARCHAR(500)        NOT NULL,
	LOOKUP_DESC                   VARCHAR(100)        NOT NULL,
	LOOKUP_SEQ                    SMALLINT,
	LOOKUP_STATUS                 CHAR(1)             NOT NULL,
	CREATED_BY                    VARCHAR(100)        NOT NULL,
	CREATED_DATE                  TIMESTAMP,
	MODIFIED_BY                   VARCHAR(100)        NOT NULL,
	MODIFIED_DATE                 TIMESTAMP);
	
Create Table SMC.SMC_DOCTYPE_MASTER(
	DOCTYPE_ID                    INTEGER             NOT NULL,
	DOC_GRP_NAME                  VARCHAR(20)         NOT NULL,
	DOC_TYPE                      VARCHAR(50)         NOT NULL,
	IS_EDITABLE                   CHAR(1)             Default 'Y',
	CREATED_BY                    VARCHAR(100)        NOT NULL,
	CREATED_DATE                  TIMESTAMP,
	MODIFIED_BY                   VARCHAR(100),
	MODIFIED_DATE                 TIMESTAMP);
	
CREATE TABLE SMC.SMC_TAB_MASTER
(
   TAB_ID int PRIMARY KEY NOT NULL,
   TAB_KEY varchar(15) NOT NULL,
   TABNAME varchar(100) NOT NULL,
   DISPLAY_SEQUENCE int NOT NULL,
   IMG_URL varchar(150),
   TEMPLATE_ID int NOT NULL,
   DASHBOARD_TAB smallint,
   STATUS char(1),
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_USER_MASTER
(
   USER_ID int PRIMARY KEY NOT NULL,
   SSO varchar(100) NOT NULL,
   GESSOUID varchar(100) NOT NULL,
   FIRST_NAME varchar(100) NOT NULL,
   LAST_NAME varchar(100) NOT NULL,
   EMAIL varchar(100) NOT NULL,
   PHONE varchar(10),
   EXTENSION varchar(5),
   STATUS char(1) NOT NULL,
   TYPE_ID int NOT NULL,
   DEPT_ID int,
   ROLE_ID int NOT NULL,
   OEM varchar(20),
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp,
   ORG_ID int NOT NULL,
   OPTDLYEML varchar(1)
);

CREATE TABLE SMC.SMC_USER_LOGIN
(
   LOGIN_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   SSO varchar(100) NOT NULL,
   SERVER_LOCATION varchar(30),
   LOGIN_TIME timestamp NOT NULL
);

CREATE TABLE SMC.SMC_USER_SECURITY
(
   USER_SECURITY_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   USER_ID int NOT NULL,
   ONE_TIME_PW varchar(100),
   NEW_USER_EMAIL_DATE timestamp,
   ACCESS_CODE varchar(6),
   ACCESS_CODE_CREATED_DATE timestamp NOT NULL,
   CREATED_BY varchar(100) NOT NULL,
   MODIFIED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_DATE timestamp NOT NULL
);

CREATE TABLE SMC.SMC_EMAIL
(
   EMAIL_AUDIT_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   USER_SSO varchar(100) NOT NULL,
   TO_ADDRESS varchar(500) NOT NULL,
   CC_ADDRESS varchar(500),
   BCC_ADDRESS varchar(500),
   EMAIL_BODY varchar(10000),
   EMAIL_SUBJECT varchar(100) NOT NULL,
   VENDOR_NUMBERS varchar(500),
   CREATED_DATE timestamp,
   CREATED_BY varchar(100) NOT NULL,
   IS_PROCESSED char(1),
   PROCESSED_DATE timestamp,
   EBS_REQUEST_ID int,
   EMAIL_TYPE VARCHAR(20) NOT NULL
)
;

CREATE TABLE SMC.SMC_EMAIL_TEMPLATE
(
   EMAIL_TEMPLATE_ID int PRIMARY KEY NOT NULL,
   EMAIL_TYPE varchar(20) NOT NULL,
   EMAIL_TEMPLATE varchar(3000) NOT NULL,
   EMAIL_SUBJECT varchar(100) NOT NULL,
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10) NOT NULL,
   MODIFIED_DATE timestamp NOT NULL
)
;

CREATE TABLE SMC.SMC_EMAIL_DOCS
(
   DOC_ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
   EMAIL_AUDIT_ID int NOT NULL,
   DOC_NAME varchar(125) NOT NULL,
   DOC_TYPE varchar(100) NOT NULL,
   DAS_ID int NOT NULL,
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL
);

CREATE TABLE SMC.SMC_SUMMARY_EMAIL_DATA
(
   CORP char(4) NOT NULL,
   VENDOR_NUMBER varchar(100),
   VENDOR_ID varchar(10) NOT NULL,
   TAB_ID int NOT NULL,
   ACTION_ITEM_ID varchar(30) NOT NULL,
   ACTION_ITEM_NAME varchar(100),
   ACTION_ITEM_COUNT int NOT NULL,
   CREATED_BY varchar(10),
   CREATED_DATE timestamp
)
;

CREATE TABLE SMC.SMC_SUMMARY_EMAIL_SSO
(
   SSO varchar(100),
   ORG_ID int NOT NULL,
   ROLE_ID varchar(100),
   IS_EMAIL_GENERATED char(1) NOT NULL,
   TOTAL_ACTION_ITEM_COUNT int,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp,
   MODIFIED_BY varchar(10) NOT NULL,
   MODIFIED_DATE timestamp
)
;

CREATE TABLE SMC.SMC_DCN_HEADER
(
   DCN_HEADER_ID int PRIMARY KEY NOT NULL,
   CORP char(4) NOT NULL,
   DCN int NOT NULL,
   IS_GENERIC_DCN char(1),
   CUSTOMER_NUMBER varchar(6),
   CUSTOMER_NAME varchar(50) NOT NULL,
   BILL_GROUP char(2),
   IN_HOUSEORDER char(1),
   PROPOSAL_ID int,
   SALESREP_ID int NOT NULL,
   MACHINE_ID int,
   BUYER_NAME varchar(100),
   BUYER_SSO varchar(10),
   ASSIGNED_DATE timestamp,
   ASSIGNED_BY varchar(10),
   CONTRACT_ANALYST varchar(100),
   IS_PRIORITIZED char(1),
   SALES_PRIORITY_NOTIFY char(1),
   VSSTATUS varchar(10),
   VSSTATUS_DATE timestamp,
   CASTATUS varchar(10),
   CASTATUS_DATE timestamp,
   IS_ORDERED char(1),
   ORDERED_DATE timestamp,
   SPEC_CONFIRMATION char(1),
   SPEC_CONF_DATE timestamp,
   SPEC_COMPLETED_DATE timestamp,
   IS_PURCHASE_REVIEW char(1),
   PUR_REVIEW_REMOVED_BY varchar(10),
   PUR_REVIEW_REMOVED_DATE timestamp,
   IS_DELETED char(1),
   DELETED_BY varchar(10),
   DELETED_DATE timestamp NOT NULL,
   CREATED_BY varchar(10),
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp,
   POPULATED_BY varchar(10),
   POPULATED_DATE timestamp,
   SPEC_CONFIRMED_BY varchar(10),
   ORDERED_BY varchar(10)
)
;

Create Table SMC.SMC_DCN_DETAIL (
	DCN_DETAIL_ID                 INTEGER             NOT NULL,
	DCN_HEADER_ID                 INTEGER             NOT NULL,
	SCH_A_NO                      VARCHAR(10),
	DEAL_ITEM_ID                  VARCHAR(10),
	ADD_UNIT_QUANTITY             INTEGER             NOT NULL,
	NEW_UNIT_QUANTITY             INTEGER             NOT NULL,
	REPLACE_UNIT_QUANTITY         INTEGER             NOT NULL,
	VS_REVIEWED                   CHAR(1),
	CA_FINALIZED                  CHAR(1),
	IS_DELETED                    CHAR(1),
	DELETED_BY                    VARCHAR(10),
	DELETED_DATE                  TIMESTAMP,
	VEHICLE_USE                   VARCHAR(10),
	SERVICE_DISTRICT              VARCHAR(6),
	IS_REVIEW_REQ                 CHAR(1),
	RATESHEET_CATEGORY            VARCHAR(15),
	RATESHEET_MAKE                VARCHAR(100),
	RATESHEET_MODEL               VARCHAR(15),
	RATESHEET_MODEL_YEAR          VARCHAR(4),
	RATESHEET_VEHICLE_TYPE        VARCHAR(20),
	REQ_DELIVERY_DATE             VARCHAR(10),
	REQ_DELIVERY_LOC              VARCHAR(50),
	CREATED_BY                    VARCHAR(10),
	CREATED_DATE                  TIMESTAMP        Default CURRENT_TIMESTAMP,
	MODIFIED_BY                   VARCHAR(10),
	MODIFIED_DATE                 TIMESTAMP);

CREATE TABLE SMC.UNIT_COMPONENTS_TEMPLATE_FOR_EXCEL
(
   ID int PRIMARY KEY NOT NULL,
   UNIT_NUMBER char(10),
   PO_NUMBER int,
   CORP char(4),
   VENDOR_NUMBER int,
   PO_CATEGORY varchar(15),
   TEMPLATE_HASH varchar(32),
   COMPONENT_ID int,
   DISPLAY_NAME varchar(100),
   COMPONENT_ACCESS char(1),
   COMPONENT_VALUE varchar(500),
   COMPONENT_TYPE char(1),
   COMPONENT_SEQUENCE int,
   UUID varchar(36)
);

CREATE TABLE SMC.SMC_ORG_MASTER
(
   ORG_ID int PRIMARY KEY NOT NULL,
   NAME varchar(50) NOT NULL,
   DESCRIPTION varchar(255),
   PARENT_ORG_ID int,
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_ORG_VENDOR_ASSOC
(
   ASSOCIATION_ID int PRIMARY KEY NOT NULL,
   ORG_ID int NOT NULL,
   VENDOR_ID int NOT NULL
)
;

CREATE TABLE SMC.SMC_ALERTS
(
   ALERT_ID int PRIMARY KEY NOT NULL,
   ALERT_KEY varchar(30) NOT NULL,
   ALERT_NAME varchar(100) NOT NULL,
   TEMPLATE_ID int,
   DISPLAY_SEQUENCE int,
   HEADER_ID int NOT NULL,
   VISIBILITY_VENDOR smallint NOT NULL,
   VISIBILITY_PENSKE smallint NOT NULL,
   ACTIONABLE smallint NOT NULL,
   HELP_TEXT varchar(255),
   MEASURE_VALUE int,
   COMPLIANCE_TEXT varchar(255)
)
;

CREATE TABLE SMC.SMC_ALERT_HEADER
(
   HEADER_ID int PRIMARY KEY NOT NULL,
   HEADER_KEY varchar(25) NOT NULL,
   HEADER_NAME varchar(50) NOT NULL,
   TAB_ID int NOT NULL,
   HELP_TEXT varchar(100),
   DISPLAY_SEQUENCE int NOT NULL
)
;


CREATE TABLE SMC.SMC_SECURITY_FUNCTION
(
   SEC_FUNC_ID int PRIMARY KEY NOT NULL,
   NAME varchar(50) NOT NULL,
   DESCRIPTION varchar(150),
   TAB_ID int,
   STATUS char(1),
   CREATED_BY varchar(100) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(100),
   MODIFIED_DATE timestamp
)
;


CREATE TABLE SMC.SMC_ROLE_SEC_FUNCTIONS
(
   SEC_FUNC_ID int NOT NULL,
   ROLE_ID int NOT NULL
)
;

CREATE TABLE SMC.SMC_LOADSHEET_HEADER
(
   LOAD_SHEET_SEQ int PRIMARY KEY NOT NULL,
   BUYER varchar(15) NOT NULL,
   PO_CATEGORY varchar(8) NOT NULL,
   PO_SUB_CATEGORY varchar(50) NOT NULL,
   SIZE varchar(8),
   VEHICLE_TYPE varchar(8),
   ORDER_MFR varchar(3),
   ORDER_QUANTITY int NOT NULL,
   ORDER_TOTAL decimal(15,2) NOT NULL,
   PURCHASE_AGREEMENT varchar(8),
   VENDOR_NUMBER int,
   FET_CODE varchar(1) NOT NULL,
   FET_AMOUNT decimal(9,2),
   FET_RATE decimal(9,4) NOT NULL,
   CURRENCY_CODE varchar(3) NOT NULL,
   EXCHANGE_RATE decimal(10,5) NOT NULL,
   BASE_PRICE decimal(9,2),
   FREIGHT decimal(9,2) NOT NULL,
   SPEC_INSTRUCTION_AMOUNT decimal(9,2) NOT NULL,
   SPEC_INSTRUCTION_FET decimal(9,2) NOT NULL,
   CORP_CODE varchar(4) NOT NULL,
   ORDER_STATUS varchar(1) NOT NULL,
   PO_NUMBER int,
   PO_DATE timestamp,
   RECORD_NUMBER int NOT NULL,
   DCN_NUMBER int NOT NULL,
   SCHEDULE_A varchar(8) NOT NULL,
   REPLACEMENT_PO varchar(1),
   TRANSPORTATION_TYPE varchar(1),
   RELEASE_TYPE varchar(1),
   PRE_ORDER varchar(1) NOT NULL,
   PRE_ORDER_REASON varchar(255),
   CREATE_TIMESTAMP timestamp NOT NULL,
   CREATE_USER varchar(15) NOT NULL,
   LAST_MAINT_TIMESTAMP timestamp NOT NULL,
   LAST_MAINT_USER varchar(15) NOT NULL,
   EXPIRATION_DATE date,
   SKIP_SERVICE_VEHICLE varchar(1),
   LEGACY_LS_SEQ int,
   PARENT_LOAD_SHEET_SEQ int
)
;

CREATE TABLE SMC.SMC_PRODUCTION_SUMMARY(
	MASTER_ID							INTEGER			NOT NULL,
	UNIT_NUMBER							VARCHAR(10)		NOT NULL,
	IS_REPLACED							VARCHAR(1)		NULL,
	VENDOR_ID							INTEGER			NULL,
	VENDOR_NUMBER						INTEGER			NULL,
	VENDOR_NAME							VARCHAR(100)	NULL,
	UNIT_VIN							VARCHAR(20)		NULL,
	CORP_CODE							VARCHAR(4)		NOT NULL,
	COUNTRY								VARCHAR(3)		NULL,
	DOMICILE_CITY						VARCHAR(20)		NULL,
	DOMICILE_STATE						VARCHAR(2)		NULL,
	PO_NUMBER							INTEGER			NOT NULL,
	PO_DATE								DATE			NULL,
	PO_CATEGORY							VARCHAR(15)		NOT NULL,
	PO_SUB_CATEGORY						VARCHAR(100)	NOT NULL,
	PRODUCTION_HOLD						VARCHAR(1)		NULL,
	OEM									VARCHAR(3)		NOT NULL,
	MODEL								VARCHAR(100)	NOT NULL,
	MODEL_YEAR							VARCHAR(4)		NOT NULL,
	VEHICLE_TYPE						VARCHAR(20)		NOT NULL,
	VEHICLE_USE							VARCHAR(20)		NOT NULL,
	UNIT_STATUS							VARCHAR(20)		NOT NULL,
	VENDOR_ORDER_NUMBER					VARCHAR(15)		NULL,
	ORG_REQ_PROD_DATE					DATE			NULL,
	ORG_REQ_DEL_DATE					DATE			NULL,
	ACT_PROD_DATE						DATE			NULL,
	ACT_DEL_DATE						DATE			NULL,
	EST_PROD_DATE						DATE			NULL,
	EST_DEL_DATE						DATE			NULL,
	PDI_RELEASE_DATE					DATE			NULL,
	PRODUCTION_DATE						VARCHAR(20)		NULL,
	DELIVERY_DATE						VARCHAR(20)		NULL,
	PRODUCTION_COMPLIANCE_DAYS			INTEGER			NOT NULL,
	DELIVERY_COMPLIANCE_DAYS			INTEGER			NOT NULL,
	CHASSIS_ESTIMATED_DELIVERY_DATE		DATE			NULL,
	CHASSIS_ACTUAL_DELIVERY_DATE		DATE			NULL,
	CUSTOMER_NAME						VARCHAR(100)	NOT NULL,
	CUSTOMER_NUMBER						VARCHAR(10)		NOT NULL,
	DESTINATION_NAME					VARCHAR(30)		NULL,
	DESTINATION_CITY					VARCHAR(30)		NULL,
	DESTINATION_STATE					VARCHAR(3)		NULL,
	TRANSPORT_TYPE						VARCHAR(20)		NULL,
	TRANSPORT_VENDOR_ID					INTEGER			NULL,
	TRANSPORT_VENDOR_NAME				VARCHAR(30)		NULL,
	TRANSPORT_STATUS					VARCHAR(3)		NULL,
	TRANSPORT_PICKUP_NOTIFICATION_DATE	DATE			NULL,
	TRANSPORT_COMMENT					VARCHAR(500)	NULL,
	TRANSPORT_COMMENT_DATE				DATE			NULL,
	ALRT_PROD_EST_PROD_PAST_DUE			VARCHAR(1)		NULL,
	ALRT_PROD_MISSING_INFO				VARCHAR(1)		NULL,
	ALRT_PROD_EST_DELV_PAST_DUE			VARCHAR(1)		NULL,
	ALRT_PROD_PROD_HOLDS				VARCHAR(1)		NULL,
	ALRT_PROD_DELV_MISSING_INFO			VARCHAR(1)		NULL,
	ALRT_PROD_DATA_CONFLICT				VARCHAR(1)		NULL,
	ALRT_PROD_DELAY_COMM_REQ			VARCHAR(1)		NULL,
	ALRT_PROD_PROD_DT_OUT_OF_RANGE		VARCHAR(1)		NULL,
	ALRT_PROD_DELV_DT_OUT_OF_RANGE		VARCHAR(1)		NULL,
	MSO_STATUS							VARCHAR(8)		NULL,
	COMMENT								VARCHAR(500)	NULL,
	COMMENT_ENTERED_DATE				DATE			NULL,
	CREATED_BY							VARCHAR(10)		NULL,
	CREATED_DATE						TIMESTAMP		NULL,
	DIRTY								VARCHAR(1)		NULL,
	LAST_REFRESH_DATE					TIMESTAMP		NULL,
	BODY_SERIAL							VARCHAR(30)		NULL,
	CHASSIS_VEHICLE_CATEGORY			VARCHAR(8)		NULL,
	CHASSIS_VEHICLE_TYPE				VARCHAR(8)		NULL,
	BODY_CUST_FURNISHED_MATERIAL		VARCHAR(30)		NULL,
	BODY_CUST_FURNISHED_DESC			VARCHAR(30)		NULL,
	MISC_CUST_FURNISHED_MATERIAL		VARCHAR(30)		NULL,
	MISC_CUST_FURNISHED_DESC			VARCHAR(30)		NULL,
	REEFER_CUST_FURNISHED_MATERIAL		VARCHAR(30)		NULL,
	REEFER_CUST_FURNISHED_DESC			VARCHAR(30)		NULL,
	COMMENT_TEXT						VARCHAR(1000)	NULL,
	COMMENT_DATE						DATE			NULL,
	CHASSIS_CUST_FURNISHED_MATERIAL		VARCHAR(30)		NULL,
	CHASSIS_CUST_FURNISHED_DESC			VARCHAR(30)		NULL,
	OEM_NAME							VARCHAR(20)		NULL,
	CHASSIS_MODEL_YEAR					INTEGER			NULL,
	CHASSIS_OEM							VARCHAR(3)		NULL,
	CHASSIS_OEM_NAME					VARCHAR(20)		NULL,
	CHASSIS_MODEL						VARCHAR(100)	NULL,
	BODY_LENGTH_IN_FEET					INTEGER			NULL,
	CUST_FURNISHED_MATERIAL				VARCHAR(30)		NULL,
	CUST_FURNISHED_DESC					VARCHAR(30)		NULL,
	PENSKE_ANALYST						VARCHAR(100)	NULL,
	DELAY_REASON						VARCHAR(50)		NULL,
	TRANSPORT_TYPE_LONG					VARCHAR(25)		NULL,
	ALRT_PROD_PROD_DT_EARLY				VARCHAR(1)		NULL,
	ALRT_PROD_PROD_DT_LATE				VARCHAR(1)		NULL,
	ALRT_PROD_DELV_DT_EARLY				VARCHAR(1)		NULL,
	ALRT_PROD_DELV_DT_LATE				VARCHAR(1)		NULL,
	IS_HOT								CHAR(1)			NOT NULL,
	IS_VISIBLE_TO_VENDOR				VARCHAR(1)		NULL,
	CHASSIS_ESTIMATED_PRODUCTION_DATE		DATE			NULL,
	CHASSIS_ACTUAL_PRODUCTION_DATE			DATE			NULL,
	COOLING_UNIT_ESTIMATED_DELIVERY_DATE	DATE			NULL,
	COOLING_UNIT_ACTUAL_DELIVERY_DATE		DATE			NULL,
	COOLING_UNIT_VENDOR_NUMBER				INTEGER			NULL,
	ALRT_ALL_MISSING_INFO					VARCHAR(1)		NULL
);

CREATE TABLE SMC.SMC_BUDDIES ( 
	SSO 					VARCHAR(10) 								 NOT NULL , 
	BUDDY_SSO				VARCHAR(10) 								 NOT NULL , 
	USER_DEPT				VARCHAR(20) 								 NOT NULL , 
	CREATED_BY				VARCHAR(10) 								 NOT NULL , 
	CREATED_DATE			TIMESTAMP 									 NULL , 
	SELECTION_TYPE			VARCHAR(20) 								 NULL
);

CREATE TABLE SMC.SMC_ORDER_FULFILLMENT_SUMMARY ( 
	DCN_HEADER_ID			INTEGER 									NOT NULL , 
	CORP_CODE 				VARCHAR(4) 									NOT NULL , 
	DCN 					INTEGER 									NOT NULL , 
	BUYER_SSO 				VARCHAR(10) 								NOT NULL , 
	VSSTATUS 				VARCHAR(10) 								NOT NULL , 
	CASTATUS 				VARCHAR(10)									NOT NULL , 
	ALRT_OF_WORKING			VARCHAR(1) 									NULL , 
	ALRT_OF_PENDED 			VARCHAR(1)									NULL , 
	ALRT_OF_READY_TO_ORDER 	VARCHAR(1)									NULL , 
	ALRT_OF_CONTRACT_RVW 	VARCHAR(1)									NULL , 
	CNT_OF_WORKING 			VARCHAR(1)									NULL , 
	CNT_OF_PENDED 			VARCHAR(1)									NULL , 
	CNT_OF_READY_TO_ORDER	VARCHAR(1)									NULL , 
	CNT_OF_CONTRACT_RVW		VARCHAR(1)									NULL , 
	CREATED_BY				VARCHAR(10) 								NULL , 
	CREATED_DATE			TIMESTAMP 									NULL , 
	DIRTY 					VARCHAR(1)									NULL , 
	LAST_REFRESH_DATE		TIMESTAMP 									NULL
);

CREATE TABLE SMC.V_SMC_UNIT_MISSING_INFO_AND_CONFLICTS_SUMS ( 
	MASTER_ID								INTEGER 									NOT NULL , 
	SUM_MISSING_INFO 						INTEGER										NOT NULL , 
	SUM_CONFLICTS 							INTEGER 									NOT NULL , 
	ALRT_PROD_MISSING_INFO_CRITERIA			VARCHAR(1) 									NOT NULL , 
	ALRT_PROD_DELV_MISSING_INFO_CRITERIA 	VARCHAR(1)									NOT NULL , 
	ALRT_PROD_DATA_CONFLICT_CRITERIA 		VARCHAR(1)									NOT NULL 
);

CREATE TABLE SMC.SMC_ORDER_CONFIRMATION_SUMMARY ( 
	HEADER_DETAIL_ID 					INTEGER 						NOT NULL , 
	CORP_CODE 							VARCHAR(4) 						NOT NULL , 
	PO_NUMBER 							INTEGER 						NOT NULL , 
	CO_NUMBER 							INTEGER 						NOT NULL , 
	CANCEL_SEQ 							INTEGER 						NOT NULL , 
	VENDOR_ID 							INTEGER 						NULL , 
	VENDOR_NUMBER 						INTEGER 						NULL , 
	VENDOR_NAME 						VARCHAR(100)					NULL , 
	VENDOR_VISIBILITY					VARCHAR(1)						NULL , 
	STATUS 								VARCHAR(10)						NOT NULL , 
	ALRT_OC_PURCHASE_ORDER 				VARCHAR(1) 						NULL , 
	ALRT_OC_CHANGE_ORDER 				VARCHAR(1) 						NULL ,  
	ALRT_OC_CANC_ORDER 					VARCHAR(1) 						NULL ,  
	CNT_OC_PURCHASE_ORDER 				VARCHAR(1) 						NULL , 
	CNT_OC_CHANGE_ORDER 				VARCHAR(1) 						NULL , 
	CNT_OC_CANC_ORDER 					VARCHAR(1) 						NULL , 
	CREATED_BY							VARCHAR(10)						NULL , 
	CREATED_DATE						TIMESTAMP						NULL , 
	DIRTY 								VARCHAR(1)						NULL , 
	LAST_REFRESH_DATE					TIMESTAMP						NULL
);

CREATE TABLE SMC.SMC_VENDOR_FILTER ( 
	VENDOR_FILTER_ID					INTEGER 						NOT NULL , 
	VENDOR_ID							INTEGER							NOT NULL , 
	USER_ID								INTEGER 						NOT NULL , 
	IS_ACTIVE							INTEGER 						NOT NULL 
);

CREATE TABLE SMC.SMC_SEARCH_TEMPLATES ( 
	TEMPLATE_ID 						INTEGER 						NOT NULL , 
	TEMPLATE_KEY 						VARCHAR(25)						NOT NULL , 
	TEMPLATE_NAME						VARCHAR(50)						NOT NULL , 
	DISPLAY_SEQUENCE					SMALLINT 						NOT NULL , 
	VISIBILITY_VENDOR					CHAR(1)							NULL , 
	VISIBILITY_PENSKE					CHAR(1)							NULL , 
	STATUS								CHAR(1)							NOT NULL , 
	CREATED_BY							VARCHAR(100)					NOT NULL , 
	CREATED_DATE						TIMESTAMP 						NOT NULL , 
	MODIFIED_BY							VARCHAR(100)					NULL , 
	MODIFIED_DATE						TIMESTAMP						NULL
);


-------- VIEWS --------
CREATE VIEW SMC.V_SMC_PO_CATEGORY_COMBINATIONS (CATEGORY, SUBCATEGORY, ASSOC_ID) AS
	SELECT B.PO_CATEGORY, C.PO_SUBCATEGORY, A.PO_CATEGORY_ASSOC_ID
	FROM SMC.SMC_PO_CATEGORY_ASSOC A
	INNER JOIN SMC.SMC_PO_CATEGORY B ON A.PO_CATEGORY_ID = B.PO_CATEGORY_ID
	INNER JOIN SMC.SMC_PO_SUBCATEGORY C ON A.PO_SUBCATEGORY_ID = C.PO_SUBCATEGORY_ID;

CREATE VIEW SMC.V_SMC_UNIT_MISSING_INFO (MASTER_ID, COMPONENT_ID) AS
	SELECT untcmp.MASTER_ID, untcmp.COMPONENT_ID
	FROM SMC.SMC_UNIT_COMPONENT untcmp
	INNER JOIN SMC.SMC_COMPONENT_INFO_DETAILS cmpdtls ON untcmp.COMPONENT_ID = cmpdtls.COMPONENT_ID
	WHERE cmpdtls.GEN_MISSING_COUNT = 'Y'
	  AND untcmp.FINAL_VISIBILITY = 'R'
	  AND untcmp.VALUE_PROVIDED = 'N';

CREATE VIEW SMC.V_SMC_UNIT_MISSING_INFO_AND_CONFLICTS (MASTER_ID ,  COMPONENT_ID , MISSING_INFO , CONFLICT , MODIFIED_DATE ) AS
    SELECT UNTCMP.MASTER_ID, UNTCMP.COMPONENT_ID,
     CASE WHEN (CMPDTLS.GEN_MISSING_COUNT = 'Y' AND UNTCMP.FINAL_VISIBILITY = 'R' AND UNTCMP.VALUE_PROVIDED = 'N') THEN 1 ELSE 0 END AS MISSING_INFO,
     CASE WHEN (UNTCMP.CONFLICT_STATUS = 'C') THEN 1 ELSE 0 END AS CONFLICT,
     UNTCMP.MODIFIED_DATE
    FROM SMC.SMC_UNIT_COMPONENT UNTCMP
    INNER JOIN SMC.SMC_COMPONENT_INFO_DETAILS CMPDTLS ON UNTCMP.COMPONENT_ID = CMPDTLS.COMPONENT_ID
    WHERE (CMPDTLS.GEN_MISSING_COUNT = 'Y'
     AND UNTCMP.FINAL_VISIBILITY = 'R'
     AND UNTCMP.VALUE_PROVIDED = 'N')
    OR (UNTCMP.CONFLICT_STATUS = 'C');